### PR TITLE
Slugify Section Names

### PR DESCRIPTION
**Pull request by jdoiro3**
This change will slugify imported section's names to have consistent URLs.

### CODE REVIEW

**Comment by froschdesign** [comment]
Is this also related to #24?

**Comment by jdoiro3** [comment]
Yes, it is.

**Comment by nejch** [comment]
@jdoiro3 @froschdesign thanks for this! Just wanted to note that without this being configurable, this is potentially a breaking change for how deep links because of how the structure is generated, IIUC. Not an issue for me, just maybe warrants a 1.0.0 then ;)

**Comment by froschdesign** [comment]
@nejch 
> Just wanted to note that without this being configurable…

Making it configurable means making it more complicated. Complicated for the maintainer and also for users.
But I see no need for _ugly_ URLs, so no configuration is required. 😃 

> …this is potentially a breaking change…

In version 0.x.x everything is allowed. :stuck_out_tongue_winking_eye:

> …just maybe warrants a 1.0.0 then…

It looks like this plugin is still in the development phase, because [there are more breaking changes](https://github.com/jdoiro3/mkdocs-multirepo-plugin/releases/tag/v0.4.0) and there might be more to come. See also in the [discussions](https://github.com/jdoiro3/mkdocs-multirepo-plugin/discussions/18).

**Comment by nejch** [comment]
Hehe that's ok @froschdesign I just wanted to note this, as end-users can get confused sometimes. Because static pages are often not explicitly versioned, it surprises people when the next deployment suddenly goes 404.

All good, I'm just maybe too used to strict semver but I just failed to notice it was still very early in dev as it was featured prominently in the plugin wiki :)

**Comment by froschdesign** [comment]
> …I'm just maybe too used to strict semver…

I too strictly follow semver, but in the initial development phase breaking changes are allowed.

> …but I just failed to notice it was still very early in dev as it was featured prominently in the plugin wiki

Right, this information is missing: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#mkdocs-multirepo-plugin

**Pull request merged**
