### PR TITLE
deep nav imports feature

### PR DESCRIPTION
**Pull request by reedsutliff**
needed this for my own personal use - hopefully it will seem like a logical feature to you.

i ran the tests in my fork and everything was passing, excluding the publish (since i dont have the pypi secret)

@jdoiro3

### CODE REVIEW

**Comment by jdoiro3** [comment]
@reedsutliff, I'm not sure if this feature is necessary since newer versions support `!imports` in the nav section that are 'deep'. You can see the test case here:

https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/76a8118bea7219d97a4a4205da799ce8ec3fe92f/tests/unittests.py#L99-L152

**Comment by jdoiro3** [comment]
This is the function that recursively looks through the nav for `!import` statements.

https://github.com/jdoiro3/mkdocs-multirepo-plugin/blob/76a8118bea7219d97a4a4205da799ce8ec3fe92f/mkdocs_multirepo_plugin/structure.py#L107-L144

**Comment by jdoiro3** [comment]
So, unless you this implementation has issues or doesn't meet your needs I'll close this PR by the end of the day.

**Comment by reedsutliff** [comment]
hey, thanks for the response.

this pull is mainly for fixing the `edit_uri` population for deep imports.

Here is the current `on_nav` function:

```python

    def on_nav(self, nav, config: Config, files: Files):
        if self.config.get("imported_repo"):
            return nav
        else:
            for f in files:
                root_src_path = get_src_path_root(f.src_path)
                if root_src_path in self.repos and f.page:
                    repo = self.repos.get(root_src_path)
                    f.page.edit_url = repo.get_edit_url(f.src_path)
            return nav
```

when `get_src_path_root` is called on a file in a deep imported repo, it fails to match against the repos dictionary.

my modified code solves this by iterating over the dictionary keys and checking them against the path.

```python

    def on_nav(self, nav, config: Config, files: Files):
        if self.config.get("imported_repo"):
            return nav
        else:
            if self.config.get("deep_nav_imports"):
                for f in files:
                    if not f.page:
                        continue
                    for key in self.repos.keys():
                        if f.src_path.startswith(key):
                            repo = self.repos.get(key)
                            f.page.edit_url = self.repos.get(key).get_edit_url(f.src_path, len(Path(key).parts))
                            break
                        
            else:
                for f in files:
                    root_src_path = get_src_path_root(f.src_path)
                    if root_src_path in self.repos and f.page:
                        repo = self.repos.get(root_src_path)
                        f.page.edit_url = repo.get_edit_url(f.src_path)
                return nav
```

**Comment by reedsutliff** [comment]
@jdoiro3 need anything from me on this request?

**Comment by jdoiro3** [comment]
> @jdoiro3 need anything from me on this request?

Not on your end unless you want to write tests, but that's something I can do. One day after work or this weekend I'll review the changes some more and write tests.

**Comment by jdoiro3** [comment]
Hey! First off, sorry for the long delay. I've been occupied by other stuff the past month or so.

@reedsutliff, could you look at this PR (i.e., try out the branch) and let me know if it fixes the issues you were encountering? I would prefer to not introduce another config value for deep imports and just handle it behind the scenes.

**Comment by jdoiro3** [comment]
Closing due to inactivity. Will re-open if needed.

**Pull request closed without merging**
