### PR TITLE
fix script execution in non-PATH directories

### PR DESCRIPTION
**Pull request by cardoe**
If the user used a virtualenv and did not have the virtualenv in their PATH. Or they used another shell like zsh and the install location of this plugin was not in bash's PATH (since it forces execution with bash) then it would just silently fail.

### CODE REVIEW

**Comment by jdoiro3** [comment]
@cardoe - thanks for contributing! Could you re-lock and push a commit so we can run tests? I'll take a look at the PR soon.

**Comment by cardoe** [comment]
> @cardoe - thanks for contributing! Could you re-lock and push a commit so we can run tests? I'll take a look at the PR soon.

Done!

**Review by jdoiro3 — APPROVED** [review]
Good changes. Thanks again!

**Comment by cardoe** [comment]
Thanks. Lemme know what I need to do to get it in a release.

**Comment by cardoe** [comment]
@jdoiro3 https://github.com/jdoiro3/mkdocs-multirepo-plugin/actions/runs/10361895254/job/28683098702 looks like the release failed. I think it should be a quick fix and just re-run CI.

**Pull request merged**
