### PR TITLE
Adds the access token for git only when executing a bash script for git

### PR DESCRIPTION
**Pull request by dhs3000**
The docs for an external repo are supposed to be included in the main menu directly without a `docs` sub menu entry. To achieve this, the contents of the `docs` folder inside a repository is moved up directly to the folder of the repo checkout.

This feature was broken as the code tried to insert the `AccessToken` for git into the first argument, even though in this case the first argument is a folder name, not a git URL. This led to the the move failing (silently).

### CODE REVIEW

**Comment by dhs3000** [comment]
@jdoiro3 I had a little older codebase when initially creating the fix, I updated my code now using the latest code including fix for #52

**Comment by dhs3000** [comment]
In both, this PR and #55 an integration tests fails with
```
"..site-packages/mkdocs_multirepo_plugin/structure.py", line 246, in _fix_edit_uri edit_uri_parts = edit_uri.strip("/").split("/") AttributeError: 'NoneType' object has no attribute 'strip'
```

But this also fails for me locally in the main branch of this repository.

**Comment by jdoiro3** [comment]
@dhs3000 looks like a newer versions of MkDocs changed how edit_uri gets populated. I'm looking into this now.

**Comment by jdoiro3** [comment]
Once this https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/56 is merged, the tests should pass.

**Comment by dhs3000** [comment]
@jdoiro3 Thanks for looking into this. I merged the main branch into this.

**Comment by jdoiro3** [comment]
@dhs3000 - for one of these PRs you’ll need to create a new release by changing the version numbers in `pyproject.toml`and `setup.py`. You should also update the CHANGELOG.

I should probably automate this stuff at some point.

**Comment by dhs3000** [comment]
@jdoiro3 I [created new release and CHANGELOG entry](https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/55/commits/3cc7ad58852bf2e176890debe36e3c5a013b0ee6) in #55

**Comment by dhs3000** [comment]
@jdoiro3 If I understand it correctly, merging #55 created already a new release, right? So I should have increased version/update changelog for this here separately? I added the bugfix of this PR to the changelog in #55 as I thought the release will happen manually after both are merged. Sorry if I misunderstood your [comment](https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/54#issuecomment-1263559315). 

let me know if I should update versions / changelog in this PR

**Comment by jdoiro3** [comment]
@dhs3000, does https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/60 replace this PR or are you still trying to get this one merged?

**Comment by dhs3000** [comment]
This PR is replaced by #60 which adds both types of access tokens to the URL inside the bash script instead of python code which is used to call all kinds of scripts.

**Pull request closed without merging**
