### PR TITLE
Adds specific GitHub access token 

### PR DESCRIPTION
**Pull request by dhs3000**
We are using a GitHub App to create an access token rather than using a personal access token (PAT). Using this token with the environment variable `AccessToken` yields the git error message `fatal: could not read Username for 'https://github.com/': No such device or address`.

This PR introduces a new `GithubAccessToken` environment variable, which is used in the git URL as `https://x-access-token:$AccessToken@github.com/....` without setting the extraheader authorization header ([GitHub docs](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#http-based-git-access-by-an-installation)).
This approach works with a PAT and an access token from a GitHub app (I tested the former locally from inside a docker container to prevent config leaking). 

The functionality for the existing `AccessToken` environment variable stays as it is, as it might be different for other environments/git servers.

----

* This addresses the issues #13 and initial description of #33.
* This replaces #54 as the access token is now inserted into the URL inside the bash script and not in `util.execute_bash_script` which is also used for moving the docs folder.

### CODE REVIEW

**Comment by jdoiro3** [comment]
Once you merge to main, CI should work.

**Comment by dhs3000** [comment]
@jdoiro3 thanks for looking into and fixing it

**Comment by dhs3000** [comment]
I can update the version info as [posted by the bot](https://github.com/jdoiro3/mkdocs-multirepo-plugin/pull/60#issuecomment-1283046134) tomorrow (away from a laptop currently)

**Comment by dhs3000** [comment]
@jdoiro3 Thanks, I added an entry to the changelog regarding this PR

**Review by jdoiro3 — APPROVED** [review]
🚀

**Pull request merged**
